//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TR.dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_RESERVA
    {
        public decimal DETALLE_RESERVA_ID { get; set; }
        public decimal RESERVA_ID { get; set; }
        public decimal PAQUETE_ID { get; set; }
    
        public virtual PAQUETE_PRODUCTO PAQUETE_PRODUCTO { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
