//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TR.dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAQUETE_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAQUETE_PRODUCTO()
        {
            this.DETALLE_RESERVA = new HashSet<DETALLE_RESERVA>();
        }
    
        public decimal PAQUETE_ID { get; set; }
        public string TRASLADO { get; set; }
        public decimal TOUR_ID { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public decimal DEPARTAMENTO_ID { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_RESERVA> DETALLE_RESERVA { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
