//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TR.dato.TurismoReal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTAMENTO()
        {
            this.DEPARTAMENTO_SERVICIO = new HashSet<DEPARTAMENTO_SERVICIO>();
            this.IMAGEN = new HashSet<IMAGEN>();
            this.PAQUETE_PRODUCTO = new HashSet<PAQUETE_PRODUCTO>();
            this.VALORACION = new HashSet<VALORACION>();
            this.ENTORNO = new HashSet<ENTORNO>();
            this.INVENTARIO = new HashSet<INVENTARIO>();
        }
    
        public decimal DEPARTAMENTO_ID { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public decimal COMUNA_ID { get; set; }
        public string SUPERFICIE { get; set; }
        public string CONDICIONES_USO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public decimal ESTADO_ID { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPARTAMENTO_SERVICIO> DEPARTAMENTO_SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGEN> IMAGEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAQUETE_PRODUCTO> PAQUETE_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VALORACION> VALORACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTORNO> ENTORNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTARIO> INVENTARIO { get; set; }
    }
}
