//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TR.dato.TurismoReal
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGEN
    {
        public decimal IMAGEN_ID { get; set; }
        public string NOMBRE_IMAGEN { get; set; }
        public decimal TOUR_ID { get; set; }
        public decimal DEPARTAMENTO_ID { get; set; }
        public decimal ENTORNO_ID { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual ENTORNO ENTORNO { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
