//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TR.dato.TurismoReal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVA()
        {
            this.DETALLE_RESERVA = new HashSet<DETALLE_RESERVA>();
            this.FACTURA = new HashSet<FACTURA>();
            this.PASAJERO = new HashSet<PASAJERO>();
            this.PASAJERO1 = new HashSet<PASAJERO>();
        }
    
        public decimal RESERVA_ID { get; set; }
        public Nullable<System.DateTime> FECHA_HORA_RESERVA { get; set; }
        public Nullable<System.DateTime> FECHA_HORA_ACTUALIZACION { get; set; }
        public string RUN_CLIENTE { get; set; }
        public string RUN_EMPLEADO { get; set; }
        public decimal ESTADO_ID { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_RESERVA> DETALLE_RESERVA { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PASAJERO> PASAJERO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PASAJERO> PASAJERO1 { get; set; }
    }
}
